### ISSUE TITLE
Storj-up import usage history

### ISSUE THREAD

**Issue by littleskunk** [storj/up#13]
Create a PR on top of https://review.dev.storj.io/c/storj/up/+/6843

To import usage data from https://storjlabs.atlassian.net/browse/SM-2743

For the beginning just import one test. We need to test out which tables are important. I assume we need bucket_bandwidth_rollups (important for invoices), bucket_storage_tallies (important for invoices), project_bandwidth_rollups (important for usage limits) [storj/projectaccounting.go at main · storj/storj](https://github.com/storj/storj/blob/main/satellite/satellitedb/projectaccounting.go) 

For traffic the action mapping shoud be:
1 = customer uploads
2 = customer download
3 = audits
4 = repair upload
5 = repair download

Config change for local test.
```
# indicates if new project dashboard should be used
console.new-project-dashboard: true
```

**Comment by nadimhq** [comment]
https://github.com/storj/up/pull/16
