### ISSUE TITLE
Add "start" command which does binary builds before starting docker, when necessary

### ISSUE THREAD

**Issue by mobyvb** [storj/up#29]
Create a new command such as `storj-up start` which
* checks for an environment variable such as `STORJ_UP_LOCAL_STORJ` or `STORJ_UP_LOCAL_GATEWAY`
* for each image in docker-compose.yaml which has volumes mounted for using local binaries, if the respective environment variable is set, attempt to build binaries
* this will be a normal `go install` on linux, or a cross compile for other operating systems. See README for specific commands
* then, start docker with `docker-compose up -d`

From a user perspective, I would like to be able to run a single command on any operating system, and if my environment is configured correctly, the build and run steps will be done.

**Comment by shaupt131** [comment]
Removing from sprint.

**Comment by elek** [comment]
It can also be implemented in the buildfiles.

For example this can be done with `earthly +deploy-local +run` which does something very similar: 

1. creates the required docker image
2. starts it with `docker-compose` up

If you would like to use local binaries, I would consider to use `storj-up init standalone`. You can have one command there (like `supervisord`) which starts a full cluster with the latest installed binaries.
