### ISSUE TITLE
Add environment file with all possible configs, similar to storj-sim

### ISSUE THREAD

**Issue by mobyvb** [storj/up#30]
`storj-sim` generates config.yaml files for satellites and storagenodes which contain every possible config that can be changed. They are all commented out by default, but you can simply uncomment a line, change the value, and save. Then, the change will go into affect as soon as you restart storj-sim.

With storj-up, you need to know the name of the flag in advance, then derive a storj-up-specific name. For example, `reputation.flush-interval` would become `STORJ_REPUTATION_FLUSH_INTERVAL`

AC:
* Add a file (or files) alongside `docker-compose.yaml` which contains all possible configs, commented out by default. I should be able to uncomment a line, change the value, and it should take effect after restarting the relevant container(s)

**Comment by dlamarmorgan** [comment]
Just as a note, this should be pretty straight forward to do with the "env_file” support of the docker compose files.

**Comment by elek** [comment]
@mobyvb Can you please give us more details about the motivation?

If the goal is just finding the right configuration value, you can do it with `storj-up configs <service>`

For example:

```
storj-up configs storagenode

...
STORJ_STORAGE2_MONITOR_VERIFY_DIR_READABLE_INTERVAL                    how frequently to verify the location and readability of the storage directory 
STORJ_STORAGE2_MONITOR_VERIFY_DIR_WRITABLE_INTERVAL                    how frequently to verify writability of storage directory
...
```

But if the goal is avoiding a copy paste from the output of `storj-up configs <service>`, or making `storj-up` compatible with `storj-sim` configuration profiles, we can certainly implement this

**Comment by mobyvb** [comment]
@elek I worked with a couple different people who knew how to use both `storj-up` and `storj-sim` for local development, and preferred `storj-sim`, and this is one of the big areas where I think using `storj-sim` is slightly preferable.
I did learn about `storj-up configs` after making this ticket, but it is still an additional step to list configs, then run a command to set a config. To make the experience of changing a config the same number of steps, it would be ideal to have a file where a config can simply be commented in and modified from a file.
I don't think it needs to be compatible with the `storj-sim` configuration profiles, unless that is the most straightforward solution. It's more that it would be nice to have a file that is already connected to `storj-up`, and which has all the configs in it already. That way I just have to ctrl+F for what I'm looking for, modify, then restart the docker containers

**Comment by stoweandi** [comment]
@mobyvb is this something we still need to do?

**Comment by mobyvb** [comment]
@stoweandi I don't think so, but I would defer to @dlamarmorgan

**Comment by dlamarmorgan** [comment]
I don't think we need this anymore, since you can now use storj-up in standalone mode, which will create a config file similar to how storj-sim does. My only hesitation is, that config file can't be used in the docker services, but maybe that's ok?

**Comment by mobyvb** [comment]
Honestly while that would be cool, I think we're fine without it. I'd say let's close this issue until/unless someone really wants it
