### ISSUE TITLE
storj-up generate invoice

### ISSUE THREAD

**Issue by littleskunk** [storj/up#33]
Similar to https://github.com/storj/up/issues/17

All we need is some fake usage for the previous month in order to be able to run the invoice command. The fake data doesn't need to be fancy. It can be a single tally result with 720 TBh of used space. -> 1 TB stored for a month.

**Comment by littleskunk** [comment]
I would expect that you have to set stripe keys
```
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_PROVIDER=stripecoinpayments
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_PUBLIC_KEY=
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_SECRET_KEY=
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_COINPAYMENTS_PUBLIC_KEY=
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_COINPAYMENTS_SECRET_KEY=
```

**Comment by ihaid** [comment]
@littleskunk here I add a line to generate bandwidth for the last day of the month https://github.com/storj/up/pull/34/files

**Comment by littleskunk** [comment]
https://github.com/storj/up/pull/34
