### ISSUE TITLE
Start using version tags

### ISSUE THREAD

**Issue by ifraixedes** [storj/up#38]
I started to use storj-up a week ago for [uplink-rust](https://github.com/storj-thirdparty/uplink-rust) CI; see https://github.com/storj-thirdparty/uplink-rust/pull/28

It worked perfectly until I merged https://github.com/storj-thirdparty/uplink-rust/pull/28 into the `main` branch and realized that those commits didn't pass the CI, but the CI passed finely with the PR.

I was digging into it and I realized that the CI of `storj-up` doesn't pass either with the same issue `429 too many requests. In the case of uplink-rust, the error is returned when running the `storj-up credentials` command.

If we would like to use storj-up in CIs, we have to start to consider tagging the repository with version tags or keeping the `main` branch always green and backward compatible, although I believe that the second is harder.

For now, I solved the issue using a specific commit, however, it isn't ideal https://github.com/storj-thirdparty/uplink-rust/pull/32

**Comment by ifraixedes** [comment]
The first tag were created in September https://github.com/storj/up/releases/tag/v1.0.0 my understanding is that from now on, we'll create tags for each new release

**Comment by elek** [comment]
> my understanding is that from now on, we'll create tags for each new release

Sure, that's the plan. After merging the version bumps on `v1` we can create one more v1 release...
