### ISSUE TITLE
No error if service doesn't exist

### ISSUE THREAD

**Issue by Erikvv** [storj/up#4]
```
$ storj-up init asasdfkjsadfkljsda
$ cat docker-compose.yaml 
version: "3.4"
services: {}
```

would be nice

**Comment by elek** [comment]
Fix is uploaded to gerrit: https://review.dev.storj.io/c/storj/up/+/6241

**Comment by elek** [comment]
Gerrit code review is updated (rev 3) for this issue. See: https://review.dev.storj.io/c/storj/up/+/6241
