### ISSUE TITLE
Feature request: dynamic default ENV variables

### ISSUE THREAD

**Issue by dlamarmorgan** [storj/up#40]
Extend the current feature that allows you to add services to the compose file, by also allowing that command to add ENV variables to other services within the compose file.

For example, if I use `storj-up add billing`  to add storjscan and geth to the compose file, also add the required ENV variables for testing billing related functionality, like the ones needed for stripe testing.

Acceptance Criteria: 
- for our current recipes ensure they have the right ENV being set in the files
    - for example, the billing receipt should have storjscan, geth, etc..

**Comment by iglesiasbrandon** [comment]
this may be solved with up v2 or at least much easier to implement.

**Comment by dlamarmorgan** [comment]
In Storj-up V2, there is a modify section of the recipe that allows you to edit env variables of other services. The add command uses this recipe as well, so this feature in fully implemented.

**Comment by iglesiasbrandon** [comment]
closing this issue because its marked as done/deployed
