### ISSUE TITLE
storj-up v2.0

### ISSUE THREAD

**Issue by elek** [storj/up#50]
This is a full refactor of storj up it can be used to generate multiple runtime descriptions. 
This is a feature branch that is supposed to be merged. it has a lot of comments and 1 small feature is missing. 
Does not support custom config file configuration. 
The biggest challenge with this patch is to get reviewers since its such a huge change. 

Acceptance Criteria: 
- fix any issues that arise from code reviews or testing
- get this patch merged
- test with storjscan
- resolve merge/ build conflicts. 

https://review.dev.storj.io/c/storj/up/+/8629

**Comment by dlamarmorgan** [comment]
I would like to help get this across the line. I will likely have some larger changes to make to storj-up soonish, and would rather make them in the V2 version than V1, otherwise rebasing may become very difficult. Let me know what I can do to help, currently I am just testing periodically.

**Comment by ifraixedes** [comment]
I'll have a look at that commit but it would take my time. My hope is to finish my review before the end of this week.

I'm not very familiar with `up` codebase so don't expect a lot of my review.

**Comment by ifraixedes** [comment]
I'm reviewing and I have a few comments. I'll finish my review tomorrow, I still have to review some sources.

**Comment by ifraixedes** [comment]
My review is done!
