### ISSUE TITLE
Update `local-ws` to support storagenode and multinode dashboards

### ISSUE THREAD

**Issue by egonelbre** [storj/up#55]
Currently using storj-up local-ws command will add the required mounts for front end development of the satellite UI. This command should be expanded to allow for specifying which front end you would like to mount, so that it can also include the storagenode and multinode dashboards.

**Comment by ifraixedes** [comment]
I think that I don't know that much about storj-up to understand what's missing.

Can you elaborate by describing a little bit about what we can do now and what we want to do?

I understand it allows us to add the front ends right now, but I don't get what's missing to mount the other front ends. Is it only mounting some specific front end and not the ones for the storagenode and multinode dashboards?

**Comment by egonelbre** [comment]
@dlamarmorgan can you clarify. I just recreated this task in storj/up.

**Comment by dlamarmorgan** [comment]
Right now, the command is hard coded to mount the front end for the satellite GUI with a single command.
see https://github.com/storj/up/blob/main/cmd/container/localbin.go#L89

We should make a similar command for mounting the files required for the other GUIs (storagenode and multinode dashboard) as well, or make the command generic enough to not need a hardcoded location if possible.
