### ISSUE TITLE
Replace storj-sim in `storj/scripts/tests/backwardcompatiblity`

### ISSUE THREAD

**Issue by egonelbre** [storj/up#65]

**Comment by dlamarmorgan** [comment]
**required storj-up tickets**
https://review.dev.storj.io/c/storj/up/+/10273
https://review.dev.storj.io/c/storj/up/+/10312
https://review.dev.storj.io/c/storj/up/+/10315
https://review.dev.storj.io/c/storj/up/+/10314
https://review.dev.storj.io/c/storj/up/+/10313
https://review.dev.storj.io/c/storj/up/+/10396
https://review.dev.storj.io/c/storj/up/+/10585
https://review.dev.storj.io/c/storj/up/+/10589
https://review.dev.storj.io/c/storj/up/+/10607
